### ISSUE TITLE
Teacher's review for week 4:

### ISSUE THREAD

**Issue by kashishchopraa** [sonakshibhalla/flask_portfolio#26]

**Comment by suneelanaidu** [comment]
Teacher's Review for week 4:
1. Good job and great team work.
2. Follow canvas requirements each week closely. Each team member had to talk in the video about their work/tangibles which gives them 2 points.
3. Keep scrum board up-to-date, add new tasks as your PBL requires and move done items to Done column etc.
4.  Do collaborate more with other teams too. 
5. Your main web page must start looking like your own "unique idea" page and each About Us page can have more features/content 
added by the individual.
6. Continue Learning/Involvement in PBL and mini labs and it will help you for the final AP Test.
7. Fix your continents dropdown, its still under Greet dropdown.

**Comment by suneelanaidu** [comment]
Your "To Do" must have all taske about your entire project. RGB requirement on binary.html(see Week 4  canvas req) was not complete, that should be on to do as well. RGB like the ASCII not the RGB minilab that Mr. M spoke to you all about.
